# Generated by Django 3.2.8 on 2021-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='이메일')),
                ('age', models.IntegerField(blank=True, verbose_name='나이')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='핸드폰 번호')),
            ],
            options={
                'verbose_name': '유저',
                'db_table': 'user',
            },
        ),
    ]
