install:
	pip install -U -r requirements.txt

env:
	direnv allow

run:
	python manage.py runserver

migration:
	python manage.py makemigrations

migrate:
	python manage.py migrate

test:
	python manage.py test
